name: continuous-integration

# run on any PR + push to develop/master
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    env:
      TARGETS: "setup.py ananse/ tests/"

    steps:
    - name: checkout ğŸ‘€
      uses: actions/checkout@v2

    - name: Install dependencies ğŸ”¨
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        use-mamba: true
        channels: conda-forge,bioconda
        channel-priority: true
        activate-environment: ananse
        environment-file: requirements.yaml

    - name: Code formatting (black) ğŸ–¤
      run: |
        black --check $(echo $TARGETS)

    - name: Code formatting (flake8) ğŸ±
      run: |
        flake8 --ignore=W503,B950 $(echo $TARGETS)

    - name: Run tests ğŸ§¬
      run: |
        pytest -vvv --disable-pytest-warnings \
        --cov=./ --cov-report=xml

    - name: Upload code coverage â˜‚ï¸
      uses: paambaati/codeclimate-action@v5
      # if: github.repository_owner == 'vanheeringen-lab'
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
