name: continuous-integration

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.8]  # [3.7, 3.8]
        os: [ubuntu-latest]  # [ubuntu-latest, macos-latest]
      fail-fast: false

    env:
      TARGETS: "ananse/ tests/"

    steps:
    - name: checkout ğŸ‘€
      uses: actions/checkout@v2

    - name: Install dependencies ğŸ”¨
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        activate-environment: ananse_dev
        environment-file: requirements.yaml

    - name: Code formatting (black) ğŸ–¤
      run: |
        black --check $(echo $TARGETS)

    - name: Code formatting (flake8) ğŸ±
      run: |
        flake8 $(echo $TARGETS)

    - name: Run tests ğŸ§¬
      run: |
        pytest -vv --disable-pytest-warnings \
        --cov=./ --cov-report=xml

    - name: Upload code coverage â˜‚ï¸
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
